/*
 * Copyright (c) TIKI Inc.
 * MIT license. See LICENSE file in root directory.
 */

export enum ButtonTextState {
  STANDARD = "STANDARD",
  STANDARD_LOADING = "STANDARD_LOADING",
  STANDARD_DISABLED = "STANDARD_DISABLED",
  BORING = "BORING",
  BORING_LOADING = "BORING_LOADING",
  BORING_DISABLED = "BORING_DISABLED",
  ALERT = "ALERT",
  ALERT_LOADING = "ALERT_LOADING",
  ALERT_DISABLED = "ALERT_DISABLED",
}
