source 'https://github.com/BlinkReceipt/PodSpecRepo.git'
source 'https://cdn.cocoapods.org/'

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'MytikiCaptureReceiptCapacitor', :path => '../../node_modules/@mytiki/capture-receipt-capacitor'
  pod 'MytikiTikiSdkCapacitor', :path => '../../node_modules/@mytiki/tiki-sdk-capacitor'
end

target 'App' do
  capacitor_pods

  pod 'BlinkReceipt', '~> 1.39'
  pod 'BlinkEReceipt', '~> 2.31'
  pod 'TikiSdkRelease', '2.1.9', :configurations => 'Release'
  pod 'TikiSdkDebug', '2.1.9', :configurations => 'Debug'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
