source 'https://github.com/BlinkReceipt/PodSpecRepo.git'
source 'https://cdn.cocoapods.org/'

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'MytikiCaptureReceiptCapacitor', :path => '../../node_modules/@mytiki/capture-receipt-capacitor'
  pod 'MytikiTikiSdkCapacitor', :path => '../../node_modules/@mytiki/tiki-sdk-capacitor'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
end

target 'App' do
  capacitor_pods
  use_frameworks!
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
